name: wxr
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.11.13
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - alembic==1.16.5
      - bottle==0.13.4
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - cloudpickle==3.1.1
      - colorlog==6.9.0
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - greenlet==3.2.4
      - gym==0.26.2
      - gym-notices==0.1.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - mako==1.3.10
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.3
      - nvidia-cublas==13.0.0.19
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.15
      - nvidia-cufile==1.15.0.42
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu13==2.28.3
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - optuna==4.5.0
      - optuna-dashboard==0.19.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - psutil==7.1.0
      - pycparser==2.23
      - pymysql==1.1.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytorch-triton==3.5.0+gitbbb06c03
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - six==1.17.0
      - sqlalchemy==2.0.43
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.10.0.dev20250928+cu130
      - torchvision==0.25.0.dev20250929+cu130
      - tqdm==4.67.1
      - transformers==4.56.2
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
prefix: /home/aizoo/miniconda3/envs/wxr
